### ISSUE TITLE
Document JSON output

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/developer.joomlatools.com#16] opened 2015-09-03 09:27 UTC
See: http://www.joomlatools.com/membercenter/forums/topic/2118-restful-api

JSON output for different views should be documented.

Mainly, everything in the data object in the response can be POSTed back in requests. Can also add a few example POST and DELETE requests.

**Comment by stevenrombauts** [comment] 2015-09-03 09:31
Putting this note/idea here because I don't really have anywhere else to put it :)

--------------------
RESTful Api documentation should potentially join the application development repositories respectively. 

i.e. joomlatools-docman/docs/json-api.md (and maybe joomlatools-docman/docs/html/ for the compiled version)

It would be a way to keep the documentation consistent with the version, and together. 
When its time to deploy the doc just run a aglio -i json-api.md -o /html/json-api.html for example.
-----

**Comment by stevenrombauts** [comment] 2015-09-03 09:31
[[image:akv8wwpNmr5jaWacwqjQWU]]

**Comment by stevenrombauts** [comment] 2015-09-03 09:31
I think we are pretty close on here. 
http://docs.docmanjson.apiary.io/

@ercanozkaya, I'd love a little feedback on the variables in the Collection part of the document. 

I've deployed *aglio* locally and its pretty straight forward. 

The default seems to be pretty close to the current template styling of http://www.joomlatools.com/extensions at the moment, but needs some obvious work to bring it in line.

**Comment by stevenrombauts** [comment] 2015-09-03 09:31
This is pretty great :)

Regarding the variables, they are all good.  For the slug it should probably say category or document slug.
Also small typo: limit should say "the number of entities" of is missing right now.

However I would make it crystal clear that they need Itemid=xx in the request. How about adding it to each individual example ? This is something people are not used to in Joomla world. Right now it is a bit easy to miss.

**Comment by stevenrombauts** [comment] 2015-09-03 09:31
@cameronbarr Excellent work. We still need to clean the Nooku docs a bit especially when we are going to start cross linking to them. I suggest in Nooku we split the documents in 2 main parts

- PHP API
- Web API

The web API would then have sub section to cover the JSON API and generic documentation about REST, JSON, Response codes etc.

**Comment by stevenrombauts** [comment] 2015-09-03 09:32
Awesome, thanks guys for the turnaround on that. 

1) I'll adjust that typo. 

2) We can probably adjust some kind of style enhancement for the Itemid note at the top of the page to make it more noticeable. Maybe even move it right to the top and/or change the wording.  

I had originally included it in each of the URI templates right at the end, i.e. /joomla3/?option=com_docman&{&view,slug,created_by,category,limit,offset,sort,direction, Itemid}, but it didn't seem to fit with that note at the top so I took it out this morning. 
Right now it is in each of the "Request" example portions  (i.e. Click on the "Get" under "Retrieve a Document" and you can see it there).

3) @johanjanssens, you're right.  For the Nooku docs, as it relates here, I should really just adjust the url at the top to point more generically to http://guides.nooku.org.  which will give us a little leeway.

**Comment by stevenrombauts** [comment] 2015-09-03 09:32
On 3, that's one option. another is to start thinking on structure now. Shouldn't be that hard to come up with something that works.

**Comment by stevenrombauts** [comment] 2015-09-03 09:32
will do  :)

**Comment by stevenrombauts** [comment] 2015-09-03 09:35
@cameronbarr Noticed you assigned this back to me, are you looking for any specific feedback on this ?

**Comment by stevenrombauts** [comment] 2015-09-03 09:39
re#16 fixing readme file symlink instructions

Branch: master
Commit: [[url:https://github.com/joomlatools/api.joomlatools.com/commit/6e2b6aab1d1f782041fcf6de7d9d82b22ff059f0|joomlatools-documentation.2:6e2b6aab1d]]

**Comment by stevenrombauts** [comment] 2015-09-03 09:48
@cameronbarr Can we already launch this documentation as a separate page based on the work you have here : http://docs.docmanjson.apiary.io/

**Comment by tomjanssens** [comment] 2015-11-30 16:24
Marked as Duplicate of https://github.com/joomlatools/developer.joomlatools.com/issues/8.

**Comment by tomjanssens** [comment] 2015-12-04 11:33
As a duplicate of #8: discontinuing this issue, closing and marked as Invalid.

This issue and the mentioned https://github.com/joomlatools/api.joomlatools.com was nothing more than a self-hosted version of an API Blueprint Markdown file.

We have the same API Blueprint Markdown on Apairy.io: http://docs.joomlatoolsdocman.apiary.io/. Cool thing of Apiary.io is that is has a [Console](https://docs.apiary.io/tools/interactive-documentation/#console) that can get data from our demo server to test API calls.

The https://github.com/joomlatools/api.joomlatools.com repository has been removed. We will focus solely on our Apiary.io documentation.

**Closed by tomjanssens** 2015-12-04 11:33 UTC
Labels: DOCman, Duplicate, Invalid

**Comment by tomjanssens** [comment] 2015-12-04 11:42
Apiary documentation work continues in #82.
